/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        ink: '#20221E',
        moss: '#33402F',
        forest: '#43503A',
        sage: '#929A7E',
        celadon: '#DCE8D8',
        ivory: '#F5F1E9',
        oat: '#E9E3D8',
        stone: '#D6D2C9',
        'mist-blue': '#BBC6C7',
        'powder-blue': '#DCE4E8',
        blush: '#D7C1BC',
        lilac: '#D9CCD9',
        butter: '#E8D66D',
        orchid: '#C78FB7',
        success: '#66805C',
        warning: '#B28A45',
        error: '#A65F59',
        info: '#71898E',
      },
      fontFamily: {
        display: ['BodoniModa_400Regular'],
        'display-italic': ['BodoniModa_400Regular_Italic'],
        'display-medium': ['BodoniModa_500Medium'],
        body: ['Manrope_400Regular'],
        'body-medium': ['Manrope_500Medium'],
        'body-semibold': ['Manrope_600SemiBold'],
        'body-bold': ['Manrope_700Bold'],
      },
      spacing: {
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
      },
      borderRadius: {
        card: '20px',
        sm: '12px',
        pill: '999px',
      },
    },
  },
  plugins: [],
};
